Mitigate HostError(TotalLogLengthExceeded { length: 120461, limit: 16384 }) error
Mitigates the following error when running the mpc-contract tests::test_signature_simple test case:

    ────────────
    Nextest run ID 8f08b400-4c94-42f4-8ebc-ab90041a2e91 with nextest profile: default
        Starting 78 tests across 7 binaries
            PASS [   0.003s] mpc-contract crypto_shared::types::test::serializeable_scalar_roundtrip
            PASS [   0.004s] mpc-contract config::tests::test_init_config_to_config_conversion
            PASS [   0.004s] mpc-contract crypto_shared::types::test::test_serialization_of_public_key_extended::case_1
            PASS [   0.004s] mpc-contract crypto_shared::types::test::test_secp256k1_signature_serialization
            PASS [   0.004s] mpc-contract crypto_shared::types::test::test_ed2519_signature_serialization
            PASS [   0.004s] mpc-contract config::tests::test_init_config_serialization
            PASS [   0.004s] mpc-contract crypto_shared::kdf::tests::test_derivation
            PASS [   0.005s] mpc-contract config::tests::test_config_serialization
            PASS [   0.003s] mpc-contract primitives::domain::tests::test_add_domains
            PASS [   0.003s] mpc-contract primitives::domain::tests::test_serialization_format
            PASS [   0.004s] mpc-contract primitives::domain::tests::test_most_recent_domain_for_signature_scheme
            PASS [   0.003s] mpc-contract primitives::key_state::tests::test_attempt_id
            PASS [   0.005s] mpc-contract primitives::domain::tests::test_retain_domains
            PASS [   0.006s] mpc-contract crypto_shared::types::test::test_serialization_of_public_key_extended::case_2
            PASS [   0.003s] mpc-contract primitives::key_state::tests::test_keyset
            PASS [   0.004s] mpc-contract primitives::participants::tests::test_migration_candidates
            PASS [   0.005s] mpc-contract primitives::key_state::tests::test_epoch_id
            PASS [   0.007s] mpc-contract primitives::participants::tests::test_migration_participants
            PASS [   0.005s] mpc-contract primitives::tee::quote::test
            PASS [   0.004s] mpc-contract primitives::test_utils::test_random_public_key
            PASS [   0.007s] mpc-contract primitives::test_utils::test_random_account_id
            PASS [   0.005s] mpc-contract primitives::thresholds::tests::test_remove_only
            PASS [   0.009s] mpc-contract primitives::thresholds::tests::test_proposal_non_contiguous_new_ids_fail
            PASS [   0.011s] mpc-contract primitives::thresholds::tests::test_migration_participants
            PASS [   0.009s] mpc-contract primitives::thresholds::tests::test_proposal_non_unique_ids
            PASS [   0.003s] mpc-contract primitives::thresholds::tests::test_threshold
            PASS [   0.006s] mpc-contract primitives::thresholds::tests::test_simultaneous_remove_and_insert
            PASS [   0.014s] mpc-contract primitives::thresholds::tests::test_new_participant_id_too_high
            PASS [   0.005s] mpc-contract primitives::thresholds::tests::test_validate_threshold
            PASS [   0.013s] mpc-contract primitives::thresholds::tests::test_validate_incoming_proposal
            PASS [   0.011s] mpc-contract primitives::votes::tests::test_voting_and_removal
            PASS [   0.034s] mpc-contract state::initializing::tests::test_cancel_key_generation
            PASS [   0.102s] mpc-contract state::initializing::tests::test_initializing_contract_state_1_0
            PASS [   0.175s] mpc-contract primitives::participants::tests::test_participants
            PASS [   0.288s] mpc-contract primitives::thresholds::tests::test_threshold_parameters_constructor
            PASS [   0.296s] mpc-contract state::initializing::tests::test_initializing_contract_state_2_1
            PASS [   0.213s] mpc-contract state::initializing::tests::test_initializing_contract_state_3_1
            PASS [   0.230s] mpc-contract state::initializing::tests::test_initializing_contract_state_3_2
            PASS [   0.410s] mpc-contract state::initializing::tests::test_initializing_contract_state_2_0
            PASS [   0.151s] mpc-contract state::resharing::tests::test_resharing_reproposal
            PASS [   0.284s] mpc-contract state::resharing::tests::test_resharing_contract_state_2
            PASS [   0.678s] mpc-contract state::initializing::tests::test_initializing_contract_state_3_0
            PASS [   0.179s] mpc-contract state::running::running_tests::test_running_0
            PASS [   0.319s] mpc-contract state::running::running_tests::test_running_2
            PASS [   0.825s] mpc-contract state::resharing::tests::test_resharing_contract_state_1
            FAIL [   0.007s] mpc-contract tests::test_signature_simple
    stdout ───

        running 1 test
        test tests::test_signature_simple ... FAILED

        failures:

        failures:
            tests::test_signature_simple

        test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 54 filtered out; finished in 0.00s

    stderr ───

        thread 'tests::test_signature_simple' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/near-sdk-5.14.0/src/environment/mock/mocked_blockchain.rs:198:78:
        called `Result::unwrap()` on an `Err` value: HostError(TotalLogLengthExceeded { length: 120461, limit: 16384 })
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    Cancelling due to test failure: 7 tests still running
            PASS [   0.927s] mpc-contract state::resharing::tests::test_resharing_contract_state_3
            PASS [   0.736s] mpc-contract state::running::running_tests::test_running_1
            PASS [   0.328s] mpc-contract state::running::running_tests::test_running_4
            PASS [   1.403s] mpc-contract primitives::key_state::tests::test_authenticated_participant_id
            PASS [   0.681s] mpc-contract state::running::running_tests::test_running_3
            PASS [   1.373s] mpc-contract state::resharing::tests::test_resharing_contract_state_4
            PASS [   2.342s] mpc-contract primitives::key_state::tests::test_authenticated_account_id
    ────────────
        Summary [   2.346s] 53/78 tests run: 52 passed, 1 failed, 0 skipped
            FAIL [   0.007s] mpc-contract tests::test_signature_simple
    warning: 25/78 tests were not run due to test failure (run with --no-fail-fast to run all tests, or run with --max-fail)
    error: test run failed